import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Konfigurasi Sidebar Vercel-style.
 * Menggunakan struktur eksplisit agar urutan dan kategori 100% terkontrol,
 * namun tetap menggunakan auto-generated untuk file di dalam sub-folder (anti-lag).
 */
const sidebars: SidebarsConfig = {
    tutorialSidebar: [
        {
            type: 'category',
            label: 'Pengantar',
            collapsed: false,
            items: ['intro'],
        },
        {
            type: 'category',
            label: 'Aturan & Format',
            collapsed: false,
            items: ['format/page', 'license'],
        },
        {
            type: 'category',
            label: 'Versi 1 (Semester 1)',
            collapsed: false,
            items: [
                'v1/index',
                {
                    type: 'category',
                    label: 'Mata Kuliah',
                    collapsed: true,
                    items: [{ type: 'autogenerated', dirName: 'v1/courses' }],
                },
                {
                    type: 'category',
                    label: 'Informasi Akademik',
                    collapsed: true,
                    items: [{ type: 'autogenerated', dirName: 'v1/information' }],
                },
                {
                    type: 'category',
                    label: 'Tugas',
                    collapsed: true,
                    items: [{ type: 'autogenerated', dirName: 'v1/task' }],
                },
            ],
        },
    ],
};

export default sidebars;
