base_url = "https://mroczect.biz.id/lectures"
title = "Lectures"
description = "Lecture notes for Software Engineering Technology, Politeknik Negeri Batam."
theme = "archie-zola"
default_language = "en"
compile_sass = true
minify_html = true
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]

taxonomies = [
  { name = "tags", feed = true },
  { name = "categories", feed = true },
]

[markdown]
smart_punctuation = true
external_links_target_blank = true
external_links_no_referrer = true

[markdown.highlighting]
theme = "one-light"
style = "inline"

[extra]
mode = "toggle"
useCDN = false
favicon = "/icon/favicon.png"
copyright = "mroczect"
custom_css = [
    "css/dark.css",
    "css/main.css",
    "css/custom.css",
]
github_repo = "mroczect/lectures"
github_branch = "master"

[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/mroczect"

[[extra.social]]
icon = "alert-circle"
name = "Issues"
url = "https://github.com/mroczect/lectures/issues"

[[extra.social]]
icon = "git-pull-request"
name = "Pull Requests"
url = "https://github.com/mroczect/lectures/pulls"

[[extra.social]]
icon = "message-square"
name = "Discussions"
url = "https://github.com/mroczect/lectures/discussions"

[[extra.social]]
icon = "mail"
name = "Email"
url = "mailto:mroczect@proton.me"

[extra.translations]
languages = []

[[extra.translations.en]]
show_more = "Read more ⟶"
previous_page = "← Previous"
next_page = "Next →"
posted_on = "on "
posted_by = "by"
read_time = "min read"
all_tags = "All tags"
menus = [
    { name = "Home",    url = "/",         weight = 1 },
    { name = "Posts",   url = "/posts",    weight = 2 },
    { name = "Tags",    url = "/tags",     weight = 3 },
    { name = "Categories", url = "/categories",  weight = 5 },
    { name = "License", url = "/license",  weight = 6 },
    { name = "About",   url = "/about",    weight = 7 },
    { name = "Changelog",   url = "/changelog",    weight = 8 },
]
