direction: right
PEGAWAI: {shape: sql_table; nopeg: string {constraint: primary_key}; nama: string}
DEPARTEMEN: {shape: sql_table; nodep: string {constraint: primary_key}; namadept: string}
PEGAWAI -> DEPARTEMEN: "mengelola (1:N)"
