direction: right
EMPLOYEE: {shape: sql_table; id: string {constraint: primary_key}; name: string; location: string}
DEPARTMENT: {shape: sql_table; deptno: string {constraint: primary_key}; deptname: string; budget: int}
EMPLOYEE -> DEPARTMENT: "work_in"
