@startuml
left to right direction
skinparam backgroundColor white
skinparam shadowing false
skinparam defaultFontName Arial
skinparam actorBackgroundColor white
skinparam actorBorderColor black
skinparam actorFontColor black
skinparam usecaseBackgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseFontColor black
skinparam rectangleBackgroundColor white
skinparam rectangleBorderColor black
skinparam rectangleFontColor black
skinparam rectangleBorderThickness 2
skinparam arrowColor black

actor "Sistem" as S

rectangle "Sistem GALONKU" {
  usecase "Simpan Riwayat Pembelian" as UC01
  usecase "Proses Pemesanan" as UC02
  usecase "Kirim Pesanan ke Agen" as UC03
  usecase "Kirim Pengingat Pemesanan Ulang" as UC04
}

S --- UC01
S --- UC02
UC02 ... UC03 : <<include>>
UC02 ... UC04 : <<include>>
@enduml
