@startuml
left to right direction
skinparam backgroundColor white
skinparam shadowing false
skinparam defaultFontName Arial
skinparam actorBackgroundColor white
skinparam actorBorderColor black
skinparam actorFontColor black
skinparam usecaseBackgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseFontColor black
skinparam rectangleBackgroundColor white
skinparam rectangleBorderColor black
skinparam rectangleFontColor black
skinparam rectangleBorderThickness 2
skinparam arrowColor black

actor "Admin / Owner" as Ad
actor "Kasir / Operator" as K

rectangle "Sistem GALONKU" {
  usecase "Lihat Stok" as UC01
  usecase "Tambah Stok" as UC02
  usecase "Kurangi Stok" as UC03
  usecase "Notifikasi Stok Menipis" as UC04
}

Ad --- UC01
Ad --- UC02
Ad --- UC03
K --- UC01
K --- UC02
K --- UC03
UC02 ... UC04 : <<extend>>
UC03 ... UC04 : <<extend>>
@enduml
