@startuml
left to right direction
skinparam backgroundColor white
skinparam shadowing false
skinparam defaultFontName Arial
skinparam actorBackgroundColor white
skinparam actorBorderColor black
skinparam actorFontColor black
skinparam usecaseBackgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseFontColor black
skinparam rectangleBackgroundColor white
skinparam rectangleBorderColor black
skinparam rectangleFontColor black
skinparam rectangleBorderThickness 2
skinparam arrowColor black

actor "Kasir / Operator" as K

rectangle "Sistem GALONKU" {
  usecase "Selesaikan Transaksi" as UC01
  usecase "Cetak Struk" as UC02
  usecase "Simpan PDF" as UC03
}

K --- UC01
K --- UC02
UC02 ... UC03 : <<extend>>
@enduml
